############### Books ################### 




### 1. Test GET all books
GET http://localhost:3000/api/books

###

### 2. Test POST (Create a new book)
POST http://localhost:3000/api/books/
Content-Type: application/json

{
  "title": "wrvqwrgfqw",
  "author": "qwegrf",
  "status": "To read"
}

###

### 3. Test GET single book (Replace 12345 with a real _id from step 1)
GET http://localhost:3000/api/books/6aacb51afb830b0dc5d

###

### 4. Test PUT (Update a book - Replace 12345 with a real _id)
PUT http://localhost:3000/api/books/6ab18af31c1d1dfde9bf58eb
Content-Type: application/json

{
  "status": "To read"
}

###

### 5. Test DELETE a book (Replace 12345 with a real _id)
DELETE http://localhost:3000/api/books/6ab18af31c1d1dfde9bf58eb




############### Users ###################




### Register a new user
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "name": "Bruce Wayne",
  "email": "batman@gotham.com",
  "password": "supersecretpassword"
}

###

### Login and get JWT
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "batman@gotham.com",
  "password": "supersecretpassword"
}